# Generated by Django 5.2.5 on 2025-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Channel Name")),
                (
                    "channel_id",
                    models.CharField(
                        help_text="Without @", max_length=100, verbose_name="Channel ID"
                    ),
                ),
                ("date_add", models.DateTimeField(verbose_name="Date Add")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
            },
        ),
    ]
